version: '3'

services:
  ui:
    container_name: portfolio-ui-prod
    build:
      context: './ui'
      dockerfile: 'Dockerfile-prod'
    networks:
      - webapp
    ports:
      - '8079:80'
  todo_app:
    container_name: portfolio-todo-app-prod
    build:
      context: './todo_app'
      dockerfile: 'Dockerfile-prod'
    networks:
      - webapp
    ports:
      - '8080:8080'
    volumes:
      - './data:/db/'
  chat_app:
    container_name: portfolio-chat-app-prod
    build:
      context: './chat_app'
      dockerfile: 'Dockerfile-prod'
    networks:
      - webapp
    ports:
      - '8081:8081'
    volumes:
      - './data:/db/'

networks:
  webapp:

