DROP TABLE IF EXISTS todo_list;
DROP TABLE IF EXISTS todo;

CREATE TABLE todo_list (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  list_name TEXT UNIQUE NOT NULL
);

CREATE TABLE todo (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  list_id INTEGER NOT NULL,
  todo TEXT NOT NULL,
  done BOOLEAN NOT NULL,
  FOREIGN KEY (list_id) REFERENCES todo_list (id)
);
